CREATE DATABASE REDBUS ;

USE REDBUS ;

CREATE TABLE DRIVER 
(
D_ID INT PRIMARY KEY ,
D_NAME VARCHAR (30),
D_VEHICLE VARCHAR (30),
D_DATE DATETIME,
D_DESTINATION VARCHAR (30),
D_FARE DOUBLE 
) ;

CREATE TABLE PASSENGER
(
P_ID INT PRIMARY KEY ,
P_NAME VARCHAR (30),
P_DATE DATETIME,
P_DESTINATION VARCHAR (30),
P_AVAILABLE VARCHAR (30),
P_FARE DOUBLE,
D_P INT,
FOREIGN KEY(D_P) REFERENCES DRIVER (D_ID)
) ;


CREATE TABLE PASS_2 SELECT * FROM PASSENGER ;

ALTER TABLE PASS_2 ADD FOREIGN KEY (D_P) REFERENCES DRIVER(D_ID) ;

SELECT * FROM DRIVER
INNER JOIN PASS_2
ON DRIVER.D_ID = PASS_2.D_P ;

SELECT * FROM DRIVER 
JOIN PASS_2
ON DRIVER.D_ID = PASS_2.D_P ;

SELECT DRIVER.D_ID,DRIVER.D_NAME,PASS_2.P_DESTINATION
FROM DRIVER 
LEFT JOIN PASS_2
ON DRIVER.D_ID = PASS_2.D_P ;

SELECT DRIVER.D_ID, DRIVER.D_NAME, DRIVER.D_VEHICLE,DRIVER.D_DATE, 
DRIVER.D_DESTINATION, DRIVER.D_FARE,PASS_2,P_NAME FROM DRIVER WHERE DRIVER.D_NAME = "DOREMI"  ;